// <auto-generated />
using System;
using HumanMotionDetection.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanMotionDetection.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HumanMotionDetection.Web.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BehaviorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<float>("ConfidenceScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BehaviorType = "Normal",
                            CameraId = "CAM-101",
                            ConfidenceScore = 0.98f,
                            CreatedDate = new DateTime(2026, 5, 19, 7, 49, 3, 887, DateTimeKind.Utc).AddTicks(8672),
                            ImagePath = "/images/sample_ok.jpg",
                            IsResolved = false,
                            Latitude = 21.028500000000001,
                            Longitude = 105.85420000000001
                        },
                        new
                        {
                            Id = 2,
                            BehaviorType = "Intruding",
                            CameraId = "CAM-102",
                            ConfidenceScore = 0.85f,
                            CreatedDate = new DateTime(2026, 5, 19, 8, 49, 3, 887, DateTimeKind.Utc).AddTicks(9364),
                            ImagePath = "/images/sample_alert.jpg",
                            IsResolved = false,
                            Latitude = 21.0305,
                            Longitude = 105.8522
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
